# Generated by Django 4.1.5 on 2024-04-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_work_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='tags',
            field=models.ManyToManyField(to='base.tag'),
        ),
    ]
