# Generated by Django 4.1.5 on 2024-04-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_work_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='static/base/images'),
        ),
    ]
